name: Build APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build Debug APK with Docker
        run: |
          docker run --rm -u $(id -u):$(id -g) -v ${{ github.workspace }}:/home/user/app \
            kivy/buildozer \
            buildozer android debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: bin/*debug*.apk

      - name: Build Release APK with Docker
        run: |
          docker run --rm -u $(id -u):$(id -g) -v ${{ github.workspace }}:/home/user/app \
            kivy/buildozer \
            buildozer android release

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: bin/*release*.apk
